packaging_format = 2

id = "elasticsearch8"
name = "ElasticSearch 8"
description.en = "Distributed and RESTful search engine"
description.fr = "Moteur de recherche RESTful"

version = "8.11.1~ynh3"

maintainers = ["fflorent"]

[upstream]
license = "SSPL-1.0"
website = "https://elastic.co"
demo = "https://www.elastic.co/demos"
admindoc = "https://www.elastic.co/guide/en/elasticsearch/reference/8.11/elasticsearch-intro.html"
code = "https://github.com/elastic/elasticsearch"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = "not_relevant"

sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

[resources]
        [resources.sources.main]
        arm64.url = "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.11.1-linux-aarch64.tar.gz"
        arm64.sha256 = "1728d26f398b58156411f80b871a2d5a0825ae446a8bec70a01a952fe7c707cb"
        amd64.url = "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.11.1-linux-x86_64.tar.gz"
        amd64.sha256 = "dd8572e4f50ffbe4079cce315b17c25e3cebaa02fd7eb134d2aa222703459780"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]

    [resources.ports]
    main.default = 9200
