packaging_format = 2

id = "elasticsearch8"
name = "ElasticSearch 8"
description.en = "Distributed and RESTful search engine"
description.fr = "Moteur de recherche RESTful"

version = "8.10.3~ynh1"

maintainers = ["fflorent"]

[upstream]
license = "SSPL-1.0"
website = "https://elastic.co"
demo = "https://www.elastic.co/demos"
admindoc = "https://www.elastic.co/guide/en/elasticsearch/reference/8.10/elasticsearch-intro.html"
code = "https://github.com/elastic/elasticsearch"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "arm64"]
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

[resources]
        [resources.sources.main]
        arm64.url = "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.10.3-linux-aarch64.tar.gz"
        arm64.sha256 = "ca965cccaabbdcb67f13a7e7b166bd7c51004c9ca55ec0ba004c475ca0024bef"
        amd64.url = "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.10.3-linux-x86_64.tar.gz"
        amd64.sha256 = "00ba66d1b67226ed87ff1c27815bb5961e352177709dd8794ef9a77b4e90a394"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]

    [resources.ports]
    main.default = 9200
